#pragma once

// Generated by tools/sync_versions.py from version.toml — do not edit.

#define BIKECOMP_FW_VERSION "0.2.0"
#define BIKECOMP_PROTO_MAJOR 1
#define BIKECOMP_PROTO_MINOR 2
#define BIKECOMP_HW_REVISION 1

#ifndef FW_VERSION
#define FW_VERSION BIKECOMP_FW_VERSION
#endif
