#!/usr/bin/env bash
# Discover local Zephyr paths and persist them in firmware-zephyr/.env.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# shellcheck source=env.sh
source "${ROOT}/scripts/env.sh"
bikecomp_load_env

MODE="write"
case "${1:-}" in
  "") ;;
  --check) MODE="check" ;;
  --print) MODE="print" ;;
  -h|--help)
    echo "Usage: $(basename "$0") [--check|--print]"
    echo "Discover Zephyr, SDK, west and U8g2 paths; default writes ${BIKECOMP_ENV_FILE}."
    exit 0
    ;;
  *)
    echo "Unknown option: $1" >&2
    exit 2
    ;;
esac

bikecomp_require_build_env

render_env() {
  echo "# Generated by scripts/configure-env.sh; local machine paths, do not commit."
  printf 'ZEPHYR_BASE=%q\n' "${ZEPHYR_BASE}"
  printf 'ZEPHYR_SDK_INSTALL_DIR=%q\n' "${ZEPHYR_SDK_INSTALL_DIR}"
  printf 'WEST_TOP=%q\n' "${WEST_TOP}"
  printf 'WEST_BIN=%q\n' "${WEST_BIN}"
  printf 'ZEPHYR_PYTHON=%q\n' "${ZEPHYR_PYTHON}"
  printf 'U8G2_ROOT=%q\n' "${U8G2_ROOT}"
  printf 'USER_CACHE_DIR=%q\n' "${USER_CACHE_DIR}"
  printf 'CCACHE_DIR=%q\n' "${CCACHE_DIR}"
  printf 'CCACHE_TEMPDIR=%q\n' "${CCACHE_TEMPDIR}"
}

if [[ "${MODE}" == "check" ]]; then
  bikecomp_print_env
  exit 0
fi

if [[ "${MODE}" == "print" ]]; then
  render_env
  exit 0
fi

temporary="$(mktemp "${BIKECOMP_ENV_FILE}.tmp.XXXXXX")"
trap 'rm -f "${temporary}"' EXIT
render_env >"${temporary}"
mv "${temporary}" "${BIKECOMP_ENV_FILE}"
trap - EXIT
echo "Wrote ${BIKECOMP_ENV_FILE}"
bikecomp_print_env
