#!/usr/bin/env python3
"""Sync version.toml into firmware, Zephyr, and mobile build files."""

from __future__ import annotations

import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION_FILE = ROOT / "version.toml"
BUILD_VERSION_H = ROOT / "firmware" / "include" / "build_version.h"
PLATFORMIO_INI = ROOT / "firmware" / "platformio.ini"
BLE_PROTOCOL_H = ROOT / "firmware" / "include" / "ble_protocol.h"
ZEPHYR_PRJ = ROOT / "firmware-zephyr" / "app" / "prj.conf"
ZEPHYR_KCONFIG = ROOT / "firmware-zephyr" / "app" / "Kconfig"
ZEPHYR_CMAKE = ROOT / "firmware-zephyr" / "app" / "CMakeLists.txt"
ZEPHYR_TEST_CMAKE = ROOT / "firmware-zephyr" / "tests" / "domain" / "CMakeLists.txt"
PUBSPEC = ROOT / "mobile-app" / "pubspec.yaml"
DEVICE_INFO_FIXTURE = ROOT / "protocol" / "fixtures" / "device_info_v1_nominal.json"


def load_versions() -> dict:
    with VERSION_FILE.open("rb") as handle:
        return tomllib.load(handle)


def replace_line(pattern: str, replacement: str, text: str, *, count: int = 0) -> str:
    updated, replacements = re.subn(
        pattern, replacement, text, count=count, flags=re.MULTILINE
    )
    if replacements == 0:
        raise RuntimeError(f"pattern not found: {pattern!r}")
    return updated


def write_build_version_h(data: dict) -> str:
    proto = data["protocol"]
    hw = data["hw"]
    arduino = data["firmware"]["arduino"]["version"]
    content = f"""#pragma once

// Generated by tools/sync_versions.py from version.toml — do not edit.

#define BIKECOMP_FW_VERSION "{arduino}"
#define BIKECOMP_PROTO_MAJOR {proto['major']}
#define BIKECOMP_PROTO_MINOR {proto['minor']}
#define BIKECOMP_HW_REVISION {hw['revision']}

#ifndef FW_VERSION
#define FW_VERSION BIKECOMP_FW_VERSION
#endif
"""
    BUILD_VERSION_H.write_text(content, encoding="utf-8")
    return content


def sync_platformio_ini(data: dict) -> None:
    proto = data["protocol"]
    hw = data["hw"]
    arduino = data["firmware"]["arduino"]["version"]
    text = PLATFORMIO_INI.read_text(encoding="utf-8")
    text = replace_line(
        r'-DFW_VERSION=\\"[^"]*\\"',
        f'-DFW_VERSION=\\"{arduino}\\"',
        text,
    )
    text = replace_line(
        r"-DPROTO_MAJOR=\d+",
        f"-DPROTO_MAJOR={proto['major']}",
        text,
    )
    text = replace_line(
        r"-DPROTO_MINOR=\d+",
        f"-DPROTO_MINOR={proto['minor']}",
        text,
    )
    text = replace_line(
        r"-DHW_REVISION=\d+",
        f"-DHW_REVISION={hw['revision']}",
        text,
    )
    PLATFORMIO_INI.write_text(text, encoding="utf-8")


def sync_ble_protocol_h(data: dict) -> None:
    proto = data["protocol"]
    text = BLE_PROTOCOL_H.read_text(encoding="utf-8")
    text = replace_line(
        r"// Mirror of protocol/data-structures\.md and protocol/uuids\.md \(protocol v[\d.]+\)\.",
        f"// Mirror of protocol/data-structures.md and protocol/uuids.md "
        f"(protocol v{proto['major']}.{proto['minor']}).",
        text,
        count=1,
    )
    text = replace_line(
        r"constexpr uint8_t kBleProtoMajor = \d+;",
        f"constexpr uint8_t kBleProtoMajor = {proto['major']};",
        text,
        count=1,
    )
    text = replace_line(
        r"constexpr uint8_t kBleProtoMinor = \d+;",
        f"constexpr uint8_t kBleProtoMinor = {proto['minor']};",
        text,
        count=1,
    )
    BLE_PROTOCOL_H.write_text(text, encoding="utf-8")


def sync_zephyr_prj(data: dict) -> None:
    zephyr = data["firmware"]["zephyr"]["version"]
    text = ZEPHYR_PRJ.read_text(encoding="utf-8")
    text = replace_line(
        r'CONFIG_FW_VERSION="[^"]*"',
        f'CONFIG_FW_VERSION="{zephyr}"',
        text,
        count=1,
    )
    ZEPHYR_PRJ.write_text(text, encoding="utf-8")


def sync_zephyr_kconfig(data: dict) -> None:
    zephyr = data["firmware"]["zephyr"]["version"]
    text = ZEPHYR_KCONFIG.read_text(encoding="utf-8")
    text = re.sub(
        r'(config FW_VERSION\n\tstring "Firmware version string"\n\tdefault ")[^"]+(")',
        rf'\g<1>{zephyr}\2',
        text,
        count=1,
    )
    ZEPHYR_KCONFIG.write_text(text, encoding="utf-8")


def sync_zephyr_cmake(path: Path, data: dict) -> None:
    proto = data["protocol"]
    hw = data["hw"]
    text = path.read_text(encoding="utf-8")
    text = replace_line(r"PROTO_MAJOR=\d+", f"PROTO_MAJOR={proto['major']}", text)
    text = replace_line(r"PROTO_MINOR=\d+", f"PROTO_MINOR={proto['minor']}", text)
    text = replace_line(r"HW_REVISION=\d+", f"HW_REVISION={hw['revision']}", text)
    path.write_text(text, encoding="utf-8")


def sync_pubspec(data: dict) -> None:
    mobile = data["mobile"]
    text = PUBSPEC.read_text(encoding="utf-8")
    text = replace_line(
        r"^version: .+$",
        f"version: {mobile['version']}+{mobile['build']}",
        text,
        count=1,
    )
    PUBSPEC.write_text(text, encoding="utf-8")


def encode_device_info_hex(fixture: dict) -> str:
    out = bytearray(48)
    out[0] = fixture["struct_version"]
    out[1] = fixture["proto_major"]
    out[2] = fixture["proto_minor"]
    out[3] = fixture["hw_revision"]
    model = fixture["model"].encode("ascii")[:16]
    out[4 : 4 + len(model)] = model
    fw = fixture["fw_version"].encode("ascii")[:12]
    out[20 : 20 + len(fw)] = fw
    serial = bytes(fixture["serial"][:8])
    out[32 : 32 + len(serial)] = serial
    uptime = int(fixture["uptime_s"])
    out[40:44] = uptime.to_bytes(4, "little")
    out[44] = fixture["reset_reason"]
    boot_count = int(fixture["boot_count"])
    out[45:47] = boot_count.to_bytes(2, "little")
    out[47] = fixture["flags"]
    return out.hex()


def sync_device_info_fixture(data: dict) -> None:
    import json

    proto = data["protocol"]
    hw = data["hw"]
    arduino = data["firmware"]["arduino"]["version"]
    fixture = json.loads(DEVICE_INFO_FIXTURE.read_text(encoding="utf-8"))
    fixture["proto_major"] = proto["major"]
    fixture["proto_minor"] = proto["minor"]
    fixture["hw_revision"] = hw["revision"]
    fixture["fw_version"] = arduino
    DEVICE_INFO_FIXTURE.write_text(
        json.dumps(fixture, indent=2, ensure_ascii=False) + "\n",
        encoding="utf-8",
    )
    hex_path = DEVICE_INFO_FIXTURE.with_suffix(".hex")
    hex_path.write_text(encode_device_info_hex(fixture) + "\n", encoding="utf-8")


def regenerate_device_info_hex() -> None:
    return None


def main() -> int:
    data = load_versions()
    write_build_version_h(data)
    sync_platformio_ini(data)
    sync_ble_protocol_h(data)
    sync_zephyr_prj(data)
    sync_zephyr_kconfig(data)
    sync_zephyr_cmake(ZEPHYR_CMAKE, data)
    sync_zephyr_cmake(ZEPHYR_TEST_CMAKE, data)
    sync_pubspec(data)
    sync_device_info_fixture(data)
    print(
        "Synced versions: "
        f"arduino={data['firmware']['arduino']['version']}, "
        f"zephyr={data['firmware']['zephyr']['version']}, "
        f"protocol={data['protocol']['major']}.{data['protocol']['minor']}, "
        f"mobile={data['mobile']['version']}+{data['mobile']['build']}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
